### ISSUE TITLE
Command-line argument documentation, help flag

### ISSUE THREAD

**Issue by JurisMajors** [JurisMajors/hostmystuff#10]
Currently, the few command arguments are not documented and there is no `--help` to display information about them. There are four arguments `--port`, `--address`, `--mongo`, `--mode`, their usages can be found in `app.js`.

Might need to change argument parsing library for displaying help menu nicely. Most arguments are self explanatory, but if you have any questions on what they exactly do, let me know.

Maybe should consider arguments parsed in a separate file and accessible globally, instead of in `app.js`.

**Comment by carewdavid** [comment]
I can do this.

**Comment by JurisMajors** [comment]
@carewdavid Sure. Let me know if you need help describing any of the arguments or help regarding anything else

**Comment by JurisMajors** [comment]
Done in #16
