### ISSUE TITLE
Disable syntax highlighting for text/html

### ISSUE THREAD

**Issue by JurisMajors** [JurisMajors/hostmystuff#11]
Title says it all. Currently syntax highlighting is enabled if the file is of mimetype text/*. should not happen if its html since its automatically rendered.

**Comment by Areadrill** [comment]
Hi! I can take this one :)

**Comment by JurisMajors** [comment]
@Areadrill go ahead :)

**Comment by JurisMajors** [comment]
@Areadrill suggest you to look at `src/fileServer.js` and function `writeToHtml`

**Comment by Areadrill** [comment]
Alright, thank you! I'll probaby deal with this either tomorrow or the day after. I may find a hole to do it tonight or tomorrow night, but I doubt it. Is that okay?

**Comment by JurisMajors** [comment]
@Areadrill All good.

**Comment by Areadrill** [comment]
Forgot to close this via the PR. Whoops

**Comment by JurisMajors** [comment]
Fixed in #17 

@Areadrill no worries :P
