### ISSUE TITLE
Better constant management

### ISSUE THREAD

**Issue by JurisMajors** [JurisMajors/hostmystuff#8]
Currently there are a lot of run-time constants. Most of them in `app.js`, but some are also scattered and awkwardly passed around to other source files.

Making a `./src/constants.js` which manages them would improve code quality and maintainability. (including run-time arguments)

**Comment by PranjalAgni** [comment]
Can I work on this?

**Comment by JurisMajors** [comment]
Go for it.

**Comment by MrCappuccino** [comment]
What about a configuration file, or command line arguments instead of hard coding into the program itself?

**Comment by MrCappuccino** [comment]
With the size of the argument/constants list, a configuration file might be a smart choice. A quick google search yields some nice tools [config](https://www.npmjs.com/package/config).

**Comment by JurisMajors** [comment]
Yes, looks interesting. This should definitely be considered, however, in a separate issue.

**Comment by JurisMajors** [comment]
Fixed in #9
